# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345
    url: jdbc:mysql://localhost:3306/myMusic?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8

  servlet:
    multipart:
      # 单个文件最大大小
      max-file-size: 50MB
      # 所有上传文件最大大小
      max-request-size: 50MB

  web:
    resources:
      static-locations: file:D:/项目/myMusic/springboot/music/,file:D:/项目/myMusic/springboot/cover/,file:D:/项目/myMusic/springboot/img/

mybatis:
  mapper-locations: classpath:mapper/*.xml # Mapper XML 文件路径
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名规则
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


jwt:
  secret: 12345678